### ISSUE TITLE
не більше 120ти символів в рядку `AboutUs.jsx`

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Akvigi/onix-react-project#2]
Бажано щоб більше в рядку було не більше 120 символів. Це гарантує нормальне відображення без горизонтального скролу майже на будь-якому моніторі

**Comment by Akvigi** [comment]
а про який горизонтальний скрол іде мова? Компонент просто розтягується або зменшується при змінні екрану

**Comment by DmitriiMelnikOnix** [comment]
А, ні, я про горизонтальний скрол в IDE 😄 
Хоча зараз занадто доврих рядків коду знайти вже не можу
